import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
  import Footer from "./components/Footer";
  import SubNav from "./components/subanav";
  import { GlobalShortcutsProvider } from "./providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
   <div className="fixed top   z-50 w-full top-0 ">
   <Navbar />
   <SubNav />
   </div>
   <GlobalShortcutsProvider>
          {children}
        </GlobalShortcutsProvider>
        <Footer />
      </body>
    </html>
  );
}
